update and delete book implemented
JelenaDinic/library-react pull request #7
Opened 2023-03-20 13:02 UTC by JelenaDinic

2023-03-20 14:06 UTC, sttevan requested changes

2023-03-20 14:06 UTC, sttevan commented on src/components/bookCard/BookCard.tsx
> +  const [ showDeleteModal, setShowDeleteModal ] = useState(false)
Sto imamo ove flag-ove odvojeno?

zasto nemamo samo show modal stanje a on nam otvara modal komponentu sa sadrzajem koji nam treba unutra

2023-03-20 14:06 UTC, sttevan commented on src/components/bookCard/BookCard.tsx
> +                <DeleteIcon onClick={() => setShowDeleteModal(true)} size={30} />
Kad bismo imali modal komponentu, onda bismo samo nju pokazali ovde a u njoj kao children prikazali ili edit ili delete

2023-03-20 14:06 UTC, sttevan commented on src/components/bookDetail/BookDetail.tsx
> +  const [ isAdmin, setIsAdmin ]  = useState(false)
Zasto ova komponenta mora da vodi racuna o tome da li je user admin, samo pozovi isUserAdmin(jwtDecode<Jwt>(token)[roleKey])

2023-03-20 14:06 UTC, sttevan commented on src/components/bookDetail/BookDetail.tsx
> +        bookService.getBookById(parseInt(params.bookId)).then((response) => {
Zasto nam je potrebna cela knjiga ako je samo brisemo?

2023-03-20 14:06 UTC, sttevan commented on src/components/bookDetail/BookDetail.tsx
> +        bookService.getBookById(parseInt(params.bookId)).then((response) => {
plus zasto je brisemo sa book details stranice a ne sa liste?

2023-03-20 14:06 UTC, sttevan commented on src/components/bookDetail/BookDetail.tsx
> +      {book &&
Sta prikazujemo na stranici ako nema knjige?

2023-03-20 14:06 UTC, sttevan commented on src/components/bookForm/BookForm.tsx
> +    console.log(bookId)
delete

2023-03-20 14:06 UTC, sttevan commented on src/components/bookForm/BookForm.tsx
>      if (bookId) {
Hajde da ne prosledjujemo ovoj komponenti samo book ID ako vec imamo celu knjigu i da je takvu i prosledimo?

2023-03-20 14:06 UTC, sttevan commented on src/components/bookForm/BookForm.tsx
>          setUpdatedBook({
Sve ovo u success-u izvuci u funkciju  gde ces setovati i knjigu i autore i cover

2023-03-20 14:06 UTC, sttevan commented on src/components/bookForm/BookForm.tsx
> +          window.location.reload()
Zasto ovo?

2023-03-20 14:06 UTC, sttevan commented on src/components/bookForm/BookForm.tsx
> +          window.location.reload()
Zasto ovo?

2023-03-20 14:06 UTC, sttevan commented on src/components/deleteBook/DeleteBook.tsx
> +    if(bookId !== 0 ) {
A sta cemo ako je id bas 0? zasto ovako radimo null checkove?

2023-03-20 14:06 UTC, sttevan commented on src/components/deleteBook/DeleteBook.tsx
> +      bookService.getBookById(bookId).then((response) => {
Kao sto rekoh, imamo celu knjigu nema ptrebe da je fetchujemo joos jednom, samo je prosledu umesto samo id-a, u komponentu

2023-03-20 14:06 UTC, sttevan commented on src/components/deleteBook/DeleteBook.tsx
> +      navigate('./Books')
sta?

2023-03-20 14:06 UTC, sttevan commented on src/components/deleteBook/DeleteBook.tsx
> +      window.location.reload()
evo ga opet ovde xD

2023-03-20 14:06 UTC, sttevan commented on src/components/editBook/EditBook.tsx
> +        <BookForm bookId={bookId} closeEditModal={closeEditModal}/>
nemamo modal "D

2023-03-20 14:06 UTC, sttevan commented on src/components/menu/Menu.tsx
> +        <NavLink to="/Books" ><BooksIcon size={25} color="#fce4db"/></NavLink>
sto je ruta velikim slovom?

2023-03-20 14:15 UTC, SaleBojke reviewed
Zasto dobijem 401 kada se pokusaju fetchovati autori?

2023-03-20 14:15 UTC, SaleBojke commented on src/App.tsx
> +                element={<route.component closeEditModal={() => {null}} filters={filters} sorting={sorting} searchInput={searchInput} setIsLogged={setIsLogged} />}
break this into multiple lines.

2023-03-20 14:17 UTC, SaleBojke commented
Kada pokusam da kreiram novog autora dobijam 401

2023-03-21 10:14 UTC, JelenaDinic commented on src/components/bookDetail/BookDetail.tsx
> +        bookService.getBookById(parseInt(params.bookId)).then((response) => {
Celu knjigu prosledjujem u delete book dialog zato sto mi pored id-a treba i title da bih da ubacila u message tog dialoga

2023-03-21 10:21 UTC, JelenaDinic commented on src/components/bookForm/BookForm.tsx
>      if (bookId) {
To nece biti isti model knjige, svakako moram da pozovem ponovo getById u toj komponenti. Jer book model iz roditeljske komponente nije isti kao book model u ovoj komponenti

2023-03-21 12:30 UTC, sttevan requested changes

2023-03-21 12:30 UTC, sttevan commented on src/App.tsx
> +    if(token) {
sto ne samo if(getToken()) ili da implementiramo u servisu prop  koji se zove isLoggedIn koja returnuje true ako ima token

2023-03-21 12:30 UTC, sttevan commented on src/components/bookCard/BookCard.tsx
> +import { isUserAdmin, isUserLibrarian } from '../../utilities/roles'
Hajde ove metode bez User jer imamo i rolu User pa je malo zbunjujuce

2023-03-21 12:30 UTC, sttevan commented on src/components/bookCard/BookCard.tsx
> +          userRole && (isUserAdmin(userRole) || isUserLibrarian(userRole)) ?
zasto ovim metodama prosledjujemo rolu, ove metopde treba da same znaju koja je rola trenutno ulogovanog usera i da samo ispljunu boolean

2023-03-21 12:30 UTC, sttevan commented on src/components/bookDetail/BookDetail.tsx
> +  userRole?: UserRole
NECEMO OVO, authServis treba da se bavi time a ne da injectujemo u sve propove svih komponenti ikada :D

2023-03-21 12:30 UTC, sttevan commented on src/components/bookDetail/BookDetail.tsx
> +              userRole && (isUserAdmin(userRole) || isUserLibrarian(userRole)) ?
i ovo isto kao i ranije

2023-03-21 12:30 UTC, sttevan commented on src/components/deleteBook/DeleteBook.tsx
> +      onModifyFinished && onModifyFinished()
navigate radimo poslednje, kad sve prodje

2023-03-21 12:30 UTC, sttevan commented on src/components/login/Login.tsx
>        setIsLogged(true)
NE NE NE :D necemo tako, nego cemo imati funkciju u servisu koja vodi racuna o tome da li je user ulogovan na osnovu toga da li je token pristan

+

setUserRole(jwtDecode<Jwt>(response.data.AccessToken)[roleKey]) 
ovo isto treba u servisu da se resi

2023-03-21 12:30 UTC, sttevan commented on src/components/menu/Menu.tsx
> +        <> {(userRole && (isUserAdmin(userRole) || isUserLibrarian(userRole))) &&
opet isto

2023-03-21 13:11 UTC, sttevan approved these changes

2023-03-21 13:12 UTC, merged